version: "3.7"

services:
  typebot_builder:
    image: baptistearno/typebot-builder:2.18.0
    networks:
      - internal_net
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ENCRYPTION_SECRET=7/l2NKGhkMUHRV0dt/g8hD2YNopCrAeH
      - DEFAULT_WORKSPACE_PLAN=UNLIMITED
      - NEXTAUTH_URL=https://typebot-auto.primora.com.br
      - NEXT_PUBLIC_VIEWER_URL=https://apibot-auto.primora.com.br
      - NEXTAUTH_URL_INTERNAL=http://localhost:3000
      - DISABLE_SIGNUP=false
      - ADMIN_EMAIL=suporte@primora.com.br
      - NEXT_PUBLIC_SMTP_FROM='Typebot' <suporte@primora.com.br>
      - SMTP_AUTH_DISABLED=false
      - SMTP_USERNAME=seuemail@gmail.com
      - SMTP_PASSWORD=suasenha
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_SECURE=true
      # Configurações do Typebot e Google Cloud
      #- GOOGLE_CLIENT_ID=
      #- GOOGLE_CLIENT_SECRET=
      # Configurações do Typebot e Minio
      - S3_ACCESS_KEY=suakey
      - S3_SECRET_KEY=suasecret
      - S3_BUCKET=typebot
      - S3_ENDPOINT=api.primora.com.br
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.typebot_builder.rule=Host(`typebot-auto.primora.com.br`)
        - traefik.http.routers.typebot_builder.entrypoints=websecure
        - traefik.http.routers.typebot_builder.tls.certresolver=letsencryptresolver
        - traefik.http.services.typebot_builder.loadbalancer.server.port=3000
        - traefik.http.services.typebot_builder.loadbalancer.passHostHeader=true
        - traefik.http.routers.typebot_builder.service=typebot_builder
networks:
  internal_net:
    external: true
    name: internal_net
