version: "3.7"

services:
  minio:
    image: quay.io/minio/minio
    secrets:
      - minio_password_secret
    command: server /data --console-address ":9001"
    networks:
      - external_net
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_PASSWORD=$MINIO_PASSWORD_FILE
      - MINIO_PASSWORD_FILE=/run/secrets/minio_password_secret
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_BROWSER_REDIRECT_URL=${MINIO_BROWSER_REDIRECT_URL}
      - MINIO_SERVER_URL=${MINIO_SERVER_URL}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.minio_public.rule=Host(`${MINIO_PUBLIC_URL}`)
        - traefik.http.routers.minio_public.entrypoints=websecure
        - traefik.http.routers.minio_public.tls.certresolver=letsencryptresolver
        - traefik.http.services.minio_public.loadbalancer.server.port=9000
        - traefik.http.services.minio_public.loadbalancer.passHostHeader=true
        - traefik.http.routers.minio_public.service=minio_public
        - traefik.http.routers.minio_console.rule=Host(`${MINIO_BROWSER_REDIRECT_URL}`)
        - traefik.http.routers.minio_console.entrypoints=websecure
        - traefik.http.routers.minio_console.tls.certresolver=letsencryptresolver
        - traefik.http.services.minio_console.loadbalancer.server.port=9001
        - traefik.http.services.minio_console.loadbalancer.passHostHeader=true
        - traefik.http.routers.minio_console.service=minio_console
volumes:
  minio_data:
    external: true
    name: minio_data

networks:
  external_net:
    external: true
    
secrets:
  minio_password_secret:
    external: true