version: "3.7"

services:
  postgres:
    image: postgres:latest
    secrets:
      - postgres_password_secret
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password_secret
    networks:
      - external_net
    #ports:
    #  - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M

volumes:
  postgres_data:
    external: true
    name: postgres_data

networks:
  external_net:
    external: true

secrets:
  postgres_password_secret:
    external: true
